name: Build & deploy

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - name: Install boto & ansible
        run: pip install boto boto3 ansible
      - name: clone devops repo
        run: git clone https://github.com/ten4ssdp/devops.git
      - name: create ssh folder
        run: |
          mkdir -p ./keys/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./keys/.ssh/id_rsa
          chmod 600 ./keys/.ssh/id_rsa
      - name: create vault key file
        run: echo "${{ secrets.VAULT_PASS }}" > ./keys/.vault_pass.txt
      - name: run ansible playbook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ANSIBLE_CFG: ./devops/ansible/ansible.cfg
          ANSIBLE_HOST_KEY_CHECKING: False
        run: ansible-playbook devops/ansible/deploy.yml -i devops/ansible/inventory/ec2.py --vault-password-file ./keys/.vault_pass.txt --key-file ./keys/.ssh/id_rsa --extra-vars "app=back executed_by_runner=yes"
