on: 
  push:
    branches:
      - devops
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v1
      # - name: build image
      #   run: docker build -t papi .
      # - name: tag image
      #   run: docker tag papi registry.kevinmanssat.fr/ssdpapi
      # - name: push image
      #   run: docker push registry.kevinmanssat.fr/ssdpapi
      - name: clone devops repo
        run: git clone https://github.com/ten4ssdp/devops.git
      - name: create ssh folder
        run: |
          mkdir -p ./keys/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./keys/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./keys/.ssh/id_rsa.pub
          chmod 600 ./keys/.ssh/id_rsa
          chmod 644 ./keys/.ssh/id_rsa.pub
          chmod 700 ./keys/.ssh
      # - name: add ssh
      #   run: |
      #     eval $(ssh-agent)
      #     ssh-add ./keys/.ssh/id_rsa
      - name: run ansible playbook
        uses: saubermacherag/ansible-playbook-docker-action@v1.2
        with:
          playbookName: './devops/ansible/deploy.yml'
          keyFile: "./keys/.ssh/id_rsa"
          inventoryFile: "./devops/ansible/inventory/hosts"
        # run: ansible-playbook -i ./devops/ansible/inventory/hosts ./devops/ansible/deploy.yml --key ./keys/.ssh/id_rsa
