name: CI

on: [pull_request, push]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - name: Lint files
        run: npm run lint
      - name: Launch tests
        run: npm run testCi
        env:
          CI: true
          DB_USERNAME: root
          DB_PASSWORD: postgres
          DB_HOST: postgres
          DB_PORT: 5432